version: '3.8'

services:
  hamachi:
    # This image must be built manually on the host first before deploying the stack.
    # See the README.md for instructions.
    image: hamachi-arm:custom
    container_name: hamachi
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      # Persists Hamachi identity and network configuration
      - hamachi-data:/var/lib/logmein-hamachi
    restart: unless-stopped

volumes:
  hamachi-data: